---
- name: iptables support
  shell: modprobe br_netfilter
- name:
  shell: |
    echo net.bridge.bridge-nf-call-ip6tables = 1 >> /etc/sysctl.conf;   
    echo net.bridge.bridge-nf-call-iptables = 1 >> /etc/sysctl.conf;
    echo net.bridge.bridge-nf-call-arptables = 1 >> /etc/sysctl.conf
- name:
  shell: sysctl –p
- name:
  shell: sysctl -w net.ipv4.ip_forward=1
- name: install ipvs
  yum:
    name:
      {{ item }}
    state: present
  with_items:
    - ipvsadm
    - ipset
    - ipset_libs

- name: ipvs support
  shell: |
     modprobe -- ip_vs;
     modprobe -- ip_vs_rr;
     modprobe -- ip_vs_wrr;
     modprobe -- ip_vs_sh;
     modprobe -- nf_conntrack_ipv4
- name: ipvs enabled
  shell: |
    echo modprobe -- ip_vs >> /etc/sysconfig/modules/ipvs.modules;
    echo modprobe -- ip_vs_rr >> /etc/sysconfig/modules/ipvs.modules;
    echo modprobe -- ip_vs_wrr >> /etc/sysconfig/modules/ipvs.modules;
    echo modprobe -- ip_vs_sh >> /etc/sysconfig/modules/ipvs.modules;
    echo modprobe -- nf_conntrack_ipv4 >> /etc/sysconfig/modules/ipvs.modules    