---
- name: remove pip directory
  file:
    path: /root/.pip/
    state: absent
- name: create pip directory
  file:
    path: /root/.pip/
    state: directory
- name: copy file to remote
  template: 
    src: "pypi.repos.j2"
    dest: "/root/.pip/pip.conf"
    mode: 0755
- name: install base packages
  pip:
    name: "{{pip_base_packages}}"
- pip:
    requirements: requirements.txt 
