---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check remote machine OS
      setup:
         gather_subset:
          - '!all'
          - '!any'
          - facter
         filter: ansible_*
    - name: Debug os information
      debug:
        msg: "{{ansible_os_family}}-{{ansible_distribution}}-{{ansible_distribution_version}}-{{ansible_architecture}}"
    - name: change hostname
      raw: "echo {{hostname|quote}} > /etc/hostname"
      when: change_hostname|default(false)
    - name:
      shell: hostname {{hostname|quote}} 
    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent
    - name: Disable swap
      command: swapoff -a      
   # - name: Install libselinux-python
   #   yum:
   #     disable_gpg_check: false
   #     name: libselinux-python
   #     state: present
   #   tags:
   #     - optimize
   #     - selinux  
    - name: turn off selinux
      selinux:
        state: disabled
      register: se
      tags:
        - optimize
        - selinux
    - name: reboot host and wait for it to return 
      shell: sleep 5 && shutdown -r now 'reboot for disable selinux'
      async: 1
      poll: 0
      ignore_errors: true
      when:
        se.reboot_required == True
    - name: Wait for the server to finish rebooting
      wait_for_connection:
        delay: 5
                     
    
