---
- name: echo date 
  shell: date "+%Y-%m-%d"
  register: date_output 
- name: "Clear Download Inventory"
  file:
    path: ./{{date_output.stdout}}-inventory.yaml
    state: absent
- name: "Download containers"
  shell: |
      echo "{{item.key}}:" >> "{{ date_output.stdout }}"-inventory.yaml
      echo "  repo: {{ download.repo }}" >> "{{ date_output.stdout }}"-inventory.yaml
      echo "  tag: {{ download.tag }}" >> "{{ date_output.stdout }}"-inventory.yaml
      echo "  container: true" >> "{{ date_output.stdout }}"-inventory.yaml
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
  with_dict: "{{ downloads }}"
  when:
    - item.value.container | default(false)
- name: "Download files"
  shell: |
      echo  "{{ item.key }}:" >> "{{ date_output.stdout }}"-inventory.yaml
      echo  "  dest: {{ download.dest }}" >> "{{ date_output.stdout }}"-inventory.yaml
      echo  "  url:  {{ download.url }}" >>"{{ date_output.stdout }}"-inventory.yaml
      echo  "  file:  true" >>"{{ date_output.stdout }}"-inventory.yaml
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
  with_dict: "{{ downloads }}"
  when:
    - item.value.file | default(false)
  
