---
insecure_registry: '20.46.87.183:5000'
docker_service_path: '/usr/lib/systemd/system/docker.service'
docker_repository_check: true
docker_repository_url: 'http://20.46.87.183:5000/v2/_catalog'
docker_repository_check_log: '/root/docker_repository.log'
docker_version: "docker-ce-18.06.2.ce-3.el7"