---
all:
   k8s-master01:
      ip: 172.17.42.95 
      ansible_user: root
      hostname: k8-master01
   k8s-master02:
      ip: 172.17.42.96 
      ansible_user: root
      hostname: k8s-master02
   k8s-master03:
      ip: 172.17.42.97 
      ansible_user: root
      hostname: k8s-master03
   k8s-node01:
      ip: 172.17.42.98 
      ansible_user: root
      hostname: k8s-node01
   k8s-node02:
      ip: 172.17.42.99 
      ansible_user: root
      hostname: k8s-node02
   k8s-node03:
      ip: 172.17.42.100  
      ansible_user: root
      hostname: k8s-node02
etcd:
   k8s-master01:
      ip: 172.17.42.95
      ansible_user: root
      hostname: k8-master01
   k8s-master02:
      ip: 172.17.42.96
      ansible_user: root
      hostname: k8s-master02
   k8s-master03:
      ip: 172.17.42.97
      ansible_user: root
      hostname: k8s-master03
kube-master:
   k8s-master01:
      ip: 172.17.42.95
      ansible_user: root
      hostname: k8-master01
   k8s-master02:
      ip: 172.17.42.96
      ansible_user: root
      hostname: k8s-master02
   k8s-master03:
      ip: 172.17.42.97
      ansible_user: root
      hostname: k8s-master03
kube-node:
   k8s-node01:
      ip: 172.17.42.98
      ansible_user: root
      hostname: k8s-node01
   k8s-node02:
      ip: 172.17.42.99
      ansible_user: root
      hostname: k8s-node02
   k8s-node03:
      ip: 172.17.42.100
      ansible_user: root
      hostname: k8s-node02


