---
- name: Gather facter
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter
    filter: ansible_*
- name: Debug os information
  debug:
    msg: "{{ansible_os_family}}-{{ansible_distribution}}-{{ansible_distribution_version}}-{{ansible_architecture}}"
- name: update /etc/hosts
  shell: echo "{{item.value.ip}} {{item.value.hostname}}" >> /etc/hosts
  with_dict: "{{all}}" 
